# Generated by Django 3.2.8 on 2021-11-01 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('season', models.CharField(blank=True, max_length=100, null=True, verbose_name='Season')),
                ('episode_number', models.IntegerField(blank=True, null=True, verbose_name='Episode number')),
                ('released', models.DateField(blank=True, null=True, verbose_name='Released')),
                ('imdbRating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='imdb Rating')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_episodes', to='series.series')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['season', 'episode_number'],
            },
        ),
    ]
