# Generated by Django 3.2.8 on 2021-10-31 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_episodes_series'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episodes',
            options={'ordering': ['season', 'episode_number'], 'verbose_name': 'Episode', 'verbose_name_plural': 'Episodes'},
        ),
        migrations.AddField(
            model_name='episodes',
            name='episode_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Episode number'),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='imdbRating',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='imdb Rating'),
        ),
        migrations.AlterField(
            model_name='episodes',
            name='season',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Season'),
        ),
    ]
