# Generated by Django 3.2.8 on 2021-10-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_alter_episodes_imdbrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodes',
            name='imdbRating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='imdb Rating'),
        ),
    ]
